# Bag of Words

### 1. Count Vectorizer

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['Grow your data science skills by competing in our exciting competitions.']

In [9]:
cvect = CountVectorizer()
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [10]:
output = cvect.fit_transform(corpus)
output

<1x11 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [11]:
output.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [12]:
cvect.vocabulary_

{'grow': 5,
 'your': 10,
 'data': 3,
 'science': 8,
 'skills': 9,
 'by': 0,
 'competing': 1,
 'in': 6,
 'our': 7,
 'exciting': 4,
 'competitions': 2}

- 불용어(Stopwords) 제거

In [13]:
# 자체 제거
cvect = CountVectorizer(stop_words=['by','in','our'])
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1]]
{'grow': 4, 'your': 7, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [14]:
# Scikit-Learn에서 제공하는 불용어 사용
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [16]:
# 최초로 nltk 작업을 한 경우에는 punkt, stopwords 모듈을 다운로드 받는다.
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [18]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw), type(sw)

(179, list)

In [19]:
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


- 인덱스에 해당하는 단어는 무엇인지 알려주는 함수

In [22]:
# 딕셔너리 반복문
voca = cvect.vocabulary_
for key in voca.keys():
    print(key, voca[key])

grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [23]:
for key, value in voca.items():
    print(key, value)

grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [24]:
def get_word(index, voca):
    for key in voca:
        if voca[key] == index:
            return key

get_word(5, cvect.vocabulary_)

'science'

In [25]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

get_word(5, cvect.vocabulary_)

'science'

- N-gram

In [26]:
text = ['I work at google.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'work': 3, 'at': 0, 'google': 2, 'work at': 4, 'at google': 1}


In [27]:
text = ['I google at work.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'google': 2, 'at': 0, 'work': 4, 'google at': 3, 'at work': 1}


In [28]:
text = ['I work at google.', 'I google at work.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 0 1 0 1 1]
 [1 0 1 1 1 1 0]]
{'work': 5, 'at': 0, 'google': 3, 'work at': 6, 'at google': 1, 'google at': 4, 'at work': 2}


### 2. TF-IDF Vectorizer

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['you know I want your love','I like you','what should I do']

In [30]:
cvect = CountVectorizer()
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [31]:
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [32]:
tvect = TfidfVectorizer(stop_words='english', ngram_range=(1,2))
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.4472136 0.4472136 0.        0.4472136 0.4472136 0.4472136]
 [0.        0.        1.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.       ]]
{'know': 0, 'want': 4, 'love': 3, 'know want': 1, 'want love': 5, 'like': 2}


In [33]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}